### ISSUE TITLE
Capmonster.cloud support

### ISSUE THREAD

**Issue by xsplas** [waslost0/twitch-autoreg#2]
Hey, can you make a capmonster.cloud support. I want top use a api key from them.

**Comment by waslost0** [comment]
> Hey, can you make a capmonster.cloud support. I want top use a api key from them.

I tried, but 
`  File "C:/Users/q/Documents/github/twitch_autoreg/twitch.py", line 186, in register
    ark_token = capmonster.joinTaskResult(taskId=taskId)
  File "C:\Users\q\AppData\Local\Programs\Python\Python38\lib\site-packages\capmonster_python\FunCaptchaTaskProxyless.py", line 47, in joinTaskResult
    self.checkResponse(response=task_result)
  File "C:\Users\q\AppData\Local\Programs\Python\Python38\lib\site-packages\capmonster_python\CapmonsterClient.py", line 27, in checkResponse
    raise CapmonsterException(error_id=response_json.get("errorId"),
capmonster_python.exceptions.CapmonsterException: [ERROR_CAPTCHA_UNSOLVABLE:1]This type of captchas is not supported by the service or the image does not contain an answer, perhaps it is too noisy. It could also mean that the image is corrupted or was incorrectly rendered. `

here is the code example
`python
pageurl = 'https://www.twitch.tv/signup?no-mobile-redirect=true&json=1'
self.caps_token = "E5554D43-23CC-1982-971D-6A2262A2CA24"
capmonster = FunCaptchaTaskProxyless(client_key=self.captcha_key)
taskId = capmonster.createTask(website_url=pageurl, website_public_key=self.caps_token)
ark_token = capmonster.joinTaskResult(taskId=taskId)
print(ark_token)
`
